FROM node:18.10.0-alpine as build

WORKDIR /usr/local/app

COPY ./ /usr/local/app

RUN npm install

RUN npm run build

FROM nginx:latest

COPY --from=build /usr/local/app/dist/s3dsim-angular /usr/share/nginx/html
COPY /config/nginx.conf  /etc/nginx/conf.d/default.conf

EXPOSE 80